
package comp603.project1;

import javax.swing.ButtonGroup;
import javax.swing.WindowConstants;

public class ClassFrame extends javax.swing.JFrame {

    UserCreatedCharacter fetchClass = UserCreatedCharacter.getInstance();
    CharacterClass classTraits = new CharacterClass();
    /**
     * Creates new form ClassFrame
     */
    public ClassFrame() {
        initComponents();
        
        //Button Group
        ButtonGroup group = new ButtonGroup(); 
        group.add(barbarianButton);
        group.add(bardButton);
        group.add(clericButton);
        group.add(druidButton);
        group.add(fighterButton);
        group.add(monkButton);
        group.add(paladinButton);
        group.add(rangerButton);
        group.add(rogueButton);
        group.add(sorcererButton);
        group.add(warlockButton);
        group.add(wizardButton);
        
        classLabel.setText("What class would you like " + fetchClass.getName() + " to be?");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classPanel = new javax.swing.JPanel();
        classLabel = new javax.swing.JLabel();
        bardButton = new javax.swing.JRadioButton();
        barbarianButton = new javax.swing.JRadioButton();
        clericButton = new javax.swing.JRadioButton();
        continueButton = new javax.swing.JButton();
        druidButton = new javax.swing.JRadioButton();
        fighterButton = new javax.swing.JRadioButton();
        monkButton = new javax.swing.JRadioButton();
        paladinButton = new javax.swing.JRadioButton();
        rangerButton = new javax.swing.JRadioButton();
        rogueButton = new javax.swing.JRadioButton();
        sorcererButton = new javax.swing.JRadioButton();
        warlockButton = new javax.swing.JRadioButton();
        wizardButton = new javax.swing.JRadioButton();
        abilitiesLabel = new javax.swing.JLabel();
        classAbilitiesLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        classLabel.setText("What Class would like your character to be?");

        bardButton.setText("Bard");
        bardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bardButtonActionPerformed(evt);
            }
        });

        barbarianButton.setText("Barbarian");
        barbarianButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barbarianButtonActionPerformed(evt);
            }
        });

        clericButton.setText("Cleric");
        clericButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clericButtonActionPerformed(evt);
            }
        });

        continueButton.setText("CONTINUE");
        continueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continueButtonActionPerformed(evt);
            }
        });

        druidButton.setText("Druid");
        druidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                druidButtonActionPerformed(evt);
            }
        });

        fighterButton.setText("Fighter");
        fighterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fighterButtonActionPerformed(evt);
            }
        });

        monkButton.setText("Monk");
        monkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monkButtonActionPerformed(evt);
            }
        });

        paladinButton.setText("Paladin");
        paladinButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paladinButtonActionPerformed(evt);
            }
        });

        rangerButton.setText("Ranger");
        rangerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rangerButtonActionPerformed(evt);
            }
        });

        rogueButton.setText("Rogue");
        rogueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rogueButtonActionPerformed(evt);
            }
        });

        sorcererButton.setText("Sorcerer");
        sorcererButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sorcererButtonActionPerformed(evt);
            }
        });

        warlockButton.setText("Warlock");
        warlockButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                warlockButtonActionPerformed(evt);
            }
        });

        wizardButton.setText("Wizard");
        wizardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wizardButtonActionPerformed(evt);
            }
        });

        abilitiesLabel.setText("Class Abilities:");

        classAbilitiesLabel.setText("...");

        javax.swing.GroupLayout classPanelLayout = new javax.swing.GroupLayout(classPanel);
        classPanel.setLayout(classPanelLayout);
        classPanelLayout.setHorizontalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, classPanelLayout.createSequentialGroup()
                .addContainerGap(115, Short.MAX_VALUE)
                .addComponent(classLabel)
                .addGap(69, 69, 69))
            .addGroup(classPanelLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classPanelLayout.createSequentialGroup()
                        .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barbarianButton)
                            .addComponent(bardButton)
                            .addComponent(clericButton)
                            .addComponent(fighterButton)
                            .addComponent(druidButton)
                            .addComponent(monkButton))
                        .addGap(26, 26, 26)
                        .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(classPanelLayout.createSequentialGroup()
                                .addComponent(wizardButton)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(classPanelLayout.createSequentialGroup()
                                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warlockButton)
                                    .addComponent(sorcererButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(continueButton)
                                .addGap(20, 20, 20))
                            .addGroup(classPanelLayout.createSequentialGroup()
                                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rogueButton)
                                    .addComponent(rangerButton)
                                    .addComponent(paladinButton))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(classPanelLayout.createSequentialGroup()
                        .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(classPanelLayout.createSequentialGroup()
                                .addComponent(abilitiesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(classAbilitiesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        classPanelLayout.setVerticalGroup(
            classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(classPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(classLabel)
                .addGap(18, 18, 18)
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barbarianButton)
                    .addComponent(paladinButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rangerButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(bardButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(clericButton)
                    .addComponent(rogueButton))
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(classPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(druidButton)
                            .addComponent(sorcererButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fighterButton)
                            .addComponent(warlockButton)))
                    .addGroup(classPanelLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(continueButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(classPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monkButton)
                    .addComponent(wizardButton))
                .addGap(18, 18, 18)
                .addComponent(abilitiesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classAbilitiesLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(classPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barbarianButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barbarianButtonActionPerformed
    classTraits.barbarian();        

   //Converts the array of class abilities to string to be printed to label
   String joined = String.join(",",fetchClass.getClassFeatures
        ());
   classAbilitiesLabel.setText(joined);  
    }//GEN-LAST:event_barbarianButtonActionPerformed

    private void bardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bardButtonActionPerformed
    classTraits.bard();
     //Converts the array of class abilities to string to be printed to label
    String joined = String.join(",",fetchClass.getClassFeatures());
    classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_bardButtonActionPerformed

    private void clericButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clericButtonActionPerformed
    classTraits.cleric();
    //Converts the array of class abilities to string to be printed to label
    String joined = String.join(",",fetchClass.getClassFeatures());
    classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_clericButtonActionPerformed

    private void continueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continueButtonActionPerformed
      
   ConclusionFrame conclusionFrame = new ConclusionFrame();
   conclusionFrame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
   conclusionFrame.setBounds(200, 200, 600, 600);
   conclusionFrame.setTitle("DND CHARACTER CREATOR");
   conclusionFrame.setVisible(true);
   
   dispose();    
    }//GEN-LAST:event_continueButtonActionPerformed

    private void druidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_druidButtonActionPerformed
    classTraits.druid();        
    //Converts the array of class abilities to string to be printed to label
    String joined = String.join(",",fetchClass.getClassFeatures());
    classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_druidButtonActionPerformed

    private void fighterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fighterButtonActionPerformed
    classTraits.fighter();
     //Converts the array of class abilities to string to be printed to label
   String joined = String.join(",",fetchClass.getClassFeatures());
   classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_fighterButtonActionPerformed

    private void monkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monkButtonActionPerformed
    classTraits.monk();
    //Converts the array of class abilities to string to be printed to label
   String joined = String.join(",",fetchClass.getClassFeatures());
   classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_monkButtonActionPerformed

    private void paladinButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paladinButtonActionPerformed
    classTraits.paladin();
     //Converts the array of class abilities to string to be printed to label
   String joined = String.join(",",fetchClass.getClassFeatures());
   classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_paladinButtonActionPerformed

    private void rangerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rangerButtonActionPerformed
    classTraits.ranger();
     //Converts the array of class abilities to string to be printed to label
   String joined = String.join(",",fetchClass.getClassFeatures());
   classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_rangerButtonActionPerformed

    private void rogueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rogueButtonActionPerformed
    classTraits.rogue();
     //Converts the array of class abilities to string to be printed to label
   String joined = String.join(",",fetchClass.getClassFeatures());
   classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_rogueButtonActionPerformed

    private void sorcererButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sorcererButtonActionPerformed
    classTraits.sorcerer(); 
     //Converts the array of class abilities to string to be printed to label
    String joined = String.join(",",fetchClass.getClassFeatures());
    classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_sorcererButtonActionPerformed

    private void warlockButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_warlockButtonActionPerformed
    classTraits.warlock();
     //Converts the array of class abilities to string to be printed to label
   String joined = String.join(",",fetchClass.getClassFeatures());
   classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_warlockButtonActionPerformed

    private void wizardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wizardButtonActionPerformed
    classTraits.wizard();
    //Converts the array of class abilities to string to be printed to label
   String joined = String.join(",",fetchClass.getClassFeatures());
   classAbilitiesLabel.setText(joined);
    }//GEN-LAST:event_wizardButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClassFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abilitiesLabel;
    private javax.swing.JRadioButton barbarianButton;
    private javax.swing.JRadioButton bardButton;
    private javax.swing.JLabel classAbilitiesLabel;
    private javax.swing.JLabel classLabel;
    private javax.swing.JPanel classPanel;
    private javax.swing.JRadioButton clericButton;
    private javax.swing.JButton continueButton;
    private javax.swing.JRadioButton druidButton;
    private javax.swing.JRadioButton fighterButton;
    private javax.swing.JRadioButton monkButton;
    private javax.swing.JRadioButton paladinButton;
    private javax.swing.JRadioButton rangerButton;
    private javax.swing.JRadioButton rogueButton;
    private javax.swing.JRadioButton sorcererButton;
    private javax.swing.JRadioButton warlockButton;
    private javax.swing.JRadioButton wizardButton;
    // End of variables declaration//GEN-END:variables
}
